spring:

  datasource:
    url: jdbc:h2:mem:empruntsdb
    driverClassName: org.h2.Driver
    username: sa
    password: "admin"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 8090