version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pretapreter-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pretapreter
      MYSQL_USER: EE
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: EE
      PMA_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
