DROP TABLE IF EXISTS utilisateur;
DROP TABLE IF EXISTS emprunt;
DROP TABLE IF EXISTS materiel;

-- Table MATERIEL
CREATE TABLE materiel
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(255) NOT NULL,
    reference     VARCHAR(255),
    etat_materiel VARCHAR(255),
    commentaire   VARCHAR(255),
    categorie     VARCHAR(255),
    date_ajout    TIMESTAMP
);

-- Table EMPRUNT
CREATE TABLE emprunt
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materiel_id         BIGINT NOT NULL,
    emprunteur          VARCHAR(255),
    date_emprunt        DATE,
    retour_prevu        DATE,
    retour_effectif     DATE,
    suivi_etat_materiel VARCHAR(255),
    commentaire         VARCHAR(255),
    CONSTRAINT fk_emprunt_materiel FOREIGN KEY (materiel_id) REFERENCES materiel (id)
);

-- Table UTILISATEUR
CREATE TABLE utilisateur
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(255) NOT NULL,
    prenom      VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    materiel_id BIGINT       NOT NULL,
    emprunt_id  BIGINT       NOT NULL,
    CONSTRAINT fk_utilisateur_materiel FOREIGN KEY (materiel_id) REFERENCES materiel (id),
    CONSTRAINT fk_utilisateur_emprunt FOREIGN KEY (emprunt_id) REFERENCES emprunt (id)
);

-- Données de test
INSERT INTO materiel (nom, reference, etat_materiel, commentaire, categorie, date_ajout)
VALUES ('Ordinateur portable', 'ASUS', 'Bon état', 'RAS', 'Informatique', CURRENT_TIMESTAMP()),
       ('Écran 24 pouces', 'LG', 'Moyen', 'Quelques rayures', 'Informatique', CURRENT_TIMESTAMP()),
       ('Clavier mécanique', 'Logitech', 'Mauvais', 'A envoyer en réparation', 'Bureautique', CURRENT_TIMESTAMP()),
       ('Switch', 'Nintendo', 'Parfait état', 'RAS', 'Console de jeu', CURRENT_TIMESTAMP());

INSERT INTO emprunt (materiel_id, emprunteur, date_emprunt, retour_prevu, retour_effectif, suivi_etat_materiel,
                     commentaire)
VALUES (1, 'Didier', '2025-10-07', '2025-10-10', '2025-10-11', 'RAS', 'RAS'),
       (2, 'Yves', '2025-10-07', '2025-10-10', '2025-10-11', 'Bon', 'Matériel en bon état'),
       (3, 'Guy', '2025-10-07', '2025-10-10', '2025-10-11', 'Mauvais', 'Défectueux'),
       (4, 'Michel', '2025-10-07', '2025-10-10', '2025-10-11', 'RAS', 'RAS');

INSERT INTO utilisateur (nom, prenom, email, materiel_id, emprunt_id)
VALUES ('Dupont', 'Didier', 'didier@exemple.com', 1, 1),
       ('Martin', 'Yves', 'yves@exemple.com', 2, 2),
       ('Durand', 'Guy', 'guy@exemple.com', 3, 3),
       ('Petit', 'Michel', 'michel@exemple.com', 4, 4);
