-- Création des tables
CREATE TABLE materiel
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(255),
    reference     VARCHAR(255),
    etat_materiel VARCHAR(255),
    commentaire   VARCHAR(255),
    categorie     VARCHAR(255),
    date_ajout    TIMESTAMP
);

CREATE TABLE utilisateur
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(255),
    prenom      VARCHAR(255),
    email       VARCHAR(255),
    materiel_id BIGINT not null,
    emprunt_id  BIGINT not null,
    CONSTRAINT fk_materiel FOREIGN KEY (materiel_id) REFERENCES materiel (id),
    CONSTRAINT fk_emprunt FOREIGN KEY (emprunt_id) REFERENCES emprunt (id)
);

CREATE TABLE emprunt
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materiel_id         BIGINT not null,
    emprunteur          VARCHAR(255),
    date_emprunt        DATE,
    retour_prevu        DATE,
    retour_effectif     DATE,
    suivi_etat_materiel VARCHAR(255),
    commentaire         VARCHAR(255),
    CONSTRAINT fk_materiel FOREIGN KEY (materiel_id) REFERENCES materiel (id)
);


-- Insertion des données
INSERT INTO materiel (nom, reference, etat_materiel, commentaire, categorie, date_ajout)
VALUES ('Ordinateur portable', 'ASUS', 'Bon état', 'RAS', 'Informatique', CURRENT_TIMESTAMP()),
       ('Ecran 24 pouces', 'LG', 'Moyen', 'Quelques rayures', 'Informatique', CURRENT_TIMESTAMP()),
       ('Clavier mécanique', 'Logitech', 'Mauvais', 'A envoyer en réparation', 'Bureautique', CURRENT_TIMESTAMP()),
       ('Switch', 'Nintendo', 'Parfait état', 'RAS', 'Console de jeu', CURRENT_TIMESTAMP());

INSERT INTO emprunt (materiel_id, emprunteur, date_emprunt, retour_prevu, retour_effectif, suivi_etat_materiel,
                     commentaire)
VALUES (1, 'Didier', '2025-10-07', '2025-10-10', '2025-10-11', 'RAS', 'RAS'),
       (2, 'Yves', '2025-10-07', '2025-10-10', '2025-10-11', 'Bon', 'Matériel en bon état'),
       (3, 'Guy', '2025-10-07', '2025-10-10', '2025-10-11', 'Mauvais', 'Défectueux'),
       (4, 'Michel', '2025-10-07', '2025-10-10', '2025-10-11', 'RAS', 'RAS');
